name: Node.js CI/CD

on:
  push:
    branches: 
      - main

jobs:
  deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Deploy using SSH
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              set -e  # Stop execution if any command fails
              source ~/.nvm/nvm.sh
              git pull
              npm install
              npm run build
              pm2 restart bookshop
